name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/my-demo-repo:${VERSION} .

      # - name: Vulnerability scan
      #   uses: aquasecurity/trivy-action@0.28.0
      #   with:
      #     image-ref: ${{ secrets.DOCKER_USERNAME }}/my-demo-repo:${{ env.VERSION }}
      #     severity: CRITICAL,HIGH
      #     exit-code: '1'
      #     ignore-unfixed: true

      - name: Push Docker image
        run: |
          docker push \
            ${{ secrets.DOCKER_USERNAME }}/my-demo-repo:${VERSION}